### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by polvi** [lane711/sonicjs#326]
Thank you for your work on this project! I am excited to try it out. 

After running your basic install command, I am getting a `process is not defined` error. Here is where I find it:

```
npx create-sonicjs@latest my-app
... yes to everything ...
npm run dev
...
✘ [ERROR] service core:user:my-sonicjs-app: Uncaught ReferenceError: process is not defined

    at null.<anonymous> (index.js:1702:11)
```

```
% node --version
v25.2.1
% wrangler --version

 ⛅️ wrangler 4.50.0
```

Any suggestions?

**Comment by everscending** [comment]
Bump.  I am getting the same error.

**Comment by everscending** [comment]
When I as Cursor to explain what's happening it tells me the following.  Not sure how to address it though...

The crash comes from the telemetry helper bundled inside @sonicjs-cms/core. When Wrangler builds your worker it executes that dependency in a Workers runtime, which doesn’t define the Node global process. The helper unconditionally reads from process.env while constructing the default telemetry config, so the very first access throws before your worker can start.

chunk-MOWI4WYE.js, Lines 2-14

var DEFAULT_TELEMETRY_CONFIG = {  
  enabled: true,  
  apiKey: process.env.POSTHOG_API_KEY || "phc_VuhFUIJLXzwyGjlgQ67dbNeSh5x4cp9F8i15hZFIDhs",  
  host: process.env.POSTHOG_HOST || "https://us.i.posthog.com",  
  debug: process.env.NODE_ENV === "development"
};
const telemetryEnv = process.env.SONICJS_TELEMETRY;

Cloudflare Workers intentionally omit process, so that direct reference causes the reported ReferenceError. Root cause: the current release of @sonicjs-cms/core assumes a Node-like environment when its telemetry config module loads, which is incompatible with the Workers runtime unless a polyfill (globalThis.process = { env: {} }) or an updated library build removes the dependency.

**Comment by ScottEAdams** [comment]
Same here:

`npx wrangler deploy --env production`

```
[ERROR] A request to the Cloudflare API .... failed
Uncaught ReferenceError: process is not defined
    at null.<anonymous>
(file:///Users/.../node_modules/.pnpm/@sonicjs-cms+core@2.0.13_@cloudflare+workers-types@4.20251125.0_drizzle-orm@0.44.7_@clo_ccf35bdc70dfe5c31fcc2815bbb1eb5e/node_modules/@sonicjs-cms/core/src/utils/telemetry-config.ts:14:11)
   [code: 10021]
```

**Comment by lane711** [comment]
Thanks guys, will look into this and resolve today

**Comment by lane711** [comment]
This has been resolved in the latest release

You can run `npm run update` to get the latest core package

**Comment by everscending** [comment]
@lane711  I'm still getting the same error after updating to @sonicjs-cms/core v2.3.3.  I've also tried removing node_modules and re-installing all of the packages.  Are there other steps I am missing?

**Comment by lane711** [comment]
Thanks for letting me know - I'll take another look

**Comment by lane711** [comment]
@everscending I am unable to reproduce this any longer. Would you be able to rerun `npx create-sonicjs my-app` and see if it still happens on a fresh install?

@ScottEAdams , @polvi would you be able to verify if running `npm run update` resolve the errors you were seeing yesterday?

**Comment by everscending** [comment]
Starting over from scratch w create-sonicjs fixed it, thanks!  A few things of note:

1) If I say Y to creating an admin user, it doesn't seem to actually create it because when I try to log into the admin panel with the credentials I gave it, it says they are invalid.  Then when I create a user via the web UI with the same credentials, it successfully creates it and I'm able to log in.

2)  pnpm run dev keeps giving me a warning about wrangler being out of date:
 ⛅️ wrangler 3.114.15 (update available 4.51.0)
---------------------------------------------------------

▲ [WARNING] The version of Wrangler you are using is now out-of-date.


3) The following migration error appeared on the first run but does not appear on subsequent runs:

[Migration] Applying 013: Code Examples Plugin
✘ [ERROR] [Migration] Error executing statement: INSERT OR IGNORE INTO code_examples (title, description, code, language, category, tags, isPublished...


✘ [ERROR] [Migration] Failed to apply migration 013: D1_ERROR: unrecognized token: "'import { useState } from ''react'';" at offset 229: SQLITE_ERROR


[Migration] Applying 014: Fix Plugin Registry

**Comment by everscending** [comment]
It did create this admin user:

<img width="1176" height="84" alt="Image" src="https://github.com/user-attachments/assets/e44b6ed6-4992-44bc-be6d-a20b4d60e5c6" />

seems like a bug

**Comment by everscending** [comment]
I see the account/login issue is addressed in #343
